version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - canonicalheader
    - cyclop
    - decorder
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - gocognit
    - gocritic
    - godot
    - godox
    - iface
    - ireturn
    - lll
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - sloglint
    - sqlclosecheck
    - unconvert
    - unused
    - wrapcheck
    - wsl_v5

  settings:
    cyclop:
      max-complexity: 15
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
    gocognit:
      min-complexity: 15
    wsl_v5:
      # Can be all | none | default | empty (per wsl v5 docs)
      default: all
