# Stage 1: Build
FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o app ./cmd/migrator

# Stage 2: Run
FROM alpine:3.20
WORKDIR /app

COPY --from=builder /app/app ./app

ENTRYPOINT ["./app"]

